Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -18,22 +18,14 @@ workflows:
       - name: Build Android release
         script: |
           chmod +x gradlew 
-
-          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME') 
-
-          if [ -z LATEST_BUILD_NUMBER ]; then 
-
-              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build 
-
-              UPDATED_BUILD_NUMBER=$BUILD_NUMBER 
-
-          else 
-
-              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1)) 
-
-          fi 
-
-          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME') 
+          if [ -z LATEST_BUILD_NUMBER ]; then 
+          # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build 
+          UPDATED_BUILD_NUMBER=$BUILD_NUMBER 
+          else 
+          UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1)) 
+          fi 
+          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
     artifacts:
       - android/app/build/outputs/apk/**/*.apk
       - android/app/build/outputs/**/*.aab 
